### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Mohammad-Reza-Rahimi-Zade** [Tiked/Client#3]
`D:\GOP>go run client.go
# _/D_/GOP/utils
utils\proc_windows.go:12:9: sI redeclared in this block
        previous declaration at utils\proc_windows.go:10:74
utils\proc_windows.go:13:9: pI redeclared in this block
        previous declaration at utils\proc_windows.go:10:74
utils\proc_windows.go:15:9: no new variables on left side of :=
utils\proc_windows.go:25:65: syntax error: unexpected newline, expecting comma or )
# github.com/SaturnsVoid/Process-Protection/process_protection
D:\Go\src\github.com\SaturnsVoid\Process-Protection\process_protection\lib.go:18:2: undefined: SetInformationProcess`

**Comment by alepacheco** [comment]
Checkout a previous commit and try again

**Comment by Mohammad-Reza-Rahimi-Zade** [comment]
How do i do this

**Comment by Mohammad-Reza-Rahimi-Zade** [comment]
???
